language: python
python:
  - "3.6"

service:
  - docker

# before_script: pip install pipenv
before_script: pip install docker-compose

script:
  # - pipenv install --skip-lock
  # - python manage.py test
  - docker-compose run app sh -c "python manage.py test"
