# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 18:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='execution_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 16, 21, 57, 52, 955927)),
        ),
    ]
