# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='name',
        ),
        migrations.AlterField(
            model_name='order',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='CRM.Master'),
        ),
    ]
