# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 17:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='name',
        ),
        migrations.AlterField(
            model_name='order',
            name='execution_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 16, 20, 43, 47, 729688)),
        ),
        migrations.AlterField(
            model_name='order',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='CRM.Master'),
        ),
    ]
