# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_auto_20181011_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='execution_date',
            field=models.DateField(),
        ),
    ]
