# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 17:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_auto_20181015_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='execution_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 16, 20, 45, 6, 21936)),
        ),
    ]
